<?php
require_once 'config.php';
requireLogin();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: index.php');
    exit();
}

$format = $_POST['format'] ?? 'pdf';
$search = $_POST['search'] ?? '';
$dateFrom = $_POST['date_from'] ?? '';
$dateTo = $_POST['date_to'] ?? '';
$data = json_decode($_POST['data'], true);

if (empty($data)) {
    header('Location: index.php');
    exit();
}

$username = $_SESSION['username'];
$date = date('Y-m-d H:i:s');

if ($format === 'excel') {
    // Export as Excel (CSV format)
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="visits_report_' . date('Y-m-d_His') . '.csv"');
    
    $output = fopen('php://output', 'w');
    
    // Add report header
    fputcsv($output, ['Visit Report']);
    fputcsv($output, ['Generated by: ' . $username]);
    fputcsv($output, ['Date: ' . $date]);
    if ($dateFrom && $dateTo) {
        fputcsv($output, ['Date Range: ' . $dateFrom . ' to ' . $dateTo]);
    } elseif ($dateFrom) {
        fputcsv($output, ['From Date: ' . $dateFrom]);
    } elseif ($dateTo) {
        fputcsv($output, ['To Date: ' . $dateTo]);
    }
    if ($search) {
        fputcsv($output, ['Search Query: ' . $search]);
    }
    fputcsv($output, ['Total Visits: ' . count($data)]);
    fputcsv($output, []); // Empty row
    
    // Add column headers
    fputcsv($output, ['Date', 'Time', 'Venue', 'Reason']);
    
    // Add data rows
    foreach ($data as $row) {
        fputcsv($output, [
            $row['date'],
            $row['time'],
            $row['venue'],
            $row['reason']
        ]);
    }
    
    fclose($output);
    exit();
}

if ($format === 'pdf') {
    // Export as PDF using FPDF
    require_once('fpdf/fpdf.php');
    
    class PDF extends FPDF {
        function Header() {
            $this->SetFont('Arial', 'B', 16);
            $this->SetTextColor(30, 60, 114);
            $this->Cell(0, 10, 'Visit Report', 0, 1, 'C');
            $this->Ln(5);
        }
        
        function Footer() {
            $this->SetY(-15);
            $this->SetFont('Arial', 'I', 8);
            $this->SetTextColor(128);
            $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
        }
        
        function InfoSection($label, $value) {
            $this->SetFont('Arial', 'B', 10);
            $this->SetTextColor(60);
            $this->Cell(40, 6, $label . ':', 0, 0);
            $this->SetFont('Arial', '', 10);
            $this->SetTextColor(0);
            $this->Cell(0, 6, $value, 0, 1);
        }
        
        function VisitTable($header, $data) {
            // Colors
            $this->SetFillColor(30, 60, 114);
            $this->SetTextColor(255);
            $this->SetDrawColor(200, 200, 200);
            $this->SetLineWidth(.3);
            $this->SetFont('Arial', 'B', 10);
            
            // Header
            $w = array(40, 45, 50, 140);
            for($i = 0; $i < count($header); $i++) {
                $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
            }
            $this->Ln();
            
            // Data
            $this->SetFillColor(248, 249, 250);
            $this->SetTextColor(0);
            $this->SetFont('Arial', '', 9);
            
            $fill = false;
            foreach($data as $row) {
                // Get the height needed for this row (for multi-line reason)
                $nb = 0;
                $nb = max($nb, $this->NbLines($w[3], $row['reason']));
                $h = 6 * max($nb, 1);
                
                // Check if we need a new page
                $this->CheckPageBreak($h);
                
                // Save the current position
                $x = $this->GetX();
                $y = $this->GetY();
                
                // Date
                $this->Cell($w[0], $h, $row['date'], 'LR', 0, 'L', $fill);
                
                // Time
                $this->Cell($w[1], $h, $row['time'], 'LR', 0, 'L', $fill);
                
                // Venue
                $this->Cell($w[2], $h, $row['venue'], 'LR', 0, 'L', $fill);
                
                // Reason - multi-line
                $this->MultiCell($w[3], 6, $row['reason'], 'LR', 'L', $fill);
                
                // Move to next line
                $this->SetXY($x, $y + $h);
                $this->Ln();
                
                $fill = !$fill;
            }
            $this->Cell(array_sum($w), 0, '', 'T');
        }
        
        function NbLines($w, $txt) {
            // Calculate the number of lines a MultiCell will take
            $cw = &$this->CurrentFont['cw'];
            if($w == 0)
                $w = $this->w - $this->rMargin - $this->x;
            $wmax = ($w - 2 * $this->cMargin) * 1000 / $this->FontSize;
            $s = str_replace("\r", '', $txt);
            $nb = strlen($s);
            if($nb > 0 && $s[$nb-1] == "\n")
                $nb--;
            $sep = -1;
            $i = 0;
            $j = 0;
            $l = 0;
            $nl = 1;
            while($i < $nb) {
                $c = $s[$i];
                if($c == "\n") {
                    $i++;
                    $sep = -1;
                    $j = $i;
                    $l = 0;
                    $nl++;
                    continue;
                }
                if($c == ' ')
                    $sep = $i;
                $l += $cw[$c];
                if($l > $wmax) {
                    if($sep == -1) {
                        if($i == $j)
                            $i++;
                    } else
                        $i = $sep + 1;
                    $sep = -1;
                    $j = $i;
                    $l = 0;
                    $nl++;
                } else
                    $i++;
            }
            return $nl;
        }
        
        function CheckPageBreak($h) {
            if($this->GetY() + $h > $this->PageBreakTrigger)
                $this->AddPage($this->CurOrientation);
        }
    }
    
    $pdf = new PDF();
    $pdf->AddPage('L'); // Landscape
    
    // Report information
    $pdf->SetFont('Arial', '', 10);
    $pdf->InfoSection('Generated by', $username);
    $pdf->InfoSection('Date', $date);
    if ($dateFrom && $dateTo) {
        $pdf->InfoSection('Date Range', $dateFrom . ' to ' . $dateTo);
    } elseif ($dateFrom) {
        $pdf->InfoSection('From Date', $dateFrom);
    } elseif ($dateTo) {
        $pdf->InfoSection('To Date', $dateTo);
    }
    if ($search) {
        $pdf->InfoSection('Search Query', $search);
    }
    $pdf->InfoSection('Total Visits', count($data));
    $pdf->Ln(5);
    
    // Table
    $header = array('Date', 'Time', 'Venue', 'Reason for Visit');
    $pdf->VisitTable($header, $data);
    
    $pdf->Output('D', 'visits_report_' . date('Y-m-d_His') . '.pdf');
    exit();
}
?>