<?php
require_once 'config.php';
requireLogin();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: index.php');
    exit();
}

$format = $_POST['format'] ?? 'pdf';
$filter = $_POST['filter'] ?? 'All';
$search = $_POST['search'] ?? '';
$data = json_decode($_POST['data'], true);

if (empty($data)) {
    header('Location: index.php');
    exit();
}

$username = $_SESSION['username'];
$date = date('Y-m-d H:i:s');

if ($format === 'excel') {
    // Export as Excel (CSV format)
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="tasks_report_' . date('Y-m-d_His') . '.csv"');
    
    $output = fopen('php://output', 'w');
    
    // Add report header
    fputcsv($output, ['Task Report']);
    fputcsv($output, ['Generated by: ' . $username]);
    fputcsv($output, ['Date: ' . $date]);
    fputcsv($output, ['Filter: ' . $filter]);
    if ($search) {
        fputcsv($output, ['Search Query: ' . $search]);
    }
    fputcsv($output, ['Total Tasks: ' . count($data)]);
    fputcsv($output, []); // Empty row
    
    // Add column headers
    fputcsv($output, ['Date', 'Project', 'Task Description', 'Priority', 'Deadline', 'Status', 'Completion']);
    
    // Add data rows
    foreach ($data as $row) {
        fputcsv($output, [
            $row['date'],
            $row['project'],
            $row['task'],
            $row['priority'],
            $row['deadline'],
            $row['status'],
            $row['completion']
        ]);
    }
    
    fclose($output);
    exit();
}

if ($format === 'pdf') {
    // Export as PDF using FPDF
    require_once('fpdf/fpdf.php');
    
    class PDF extends FPDF {
        function Header() {
            $this->SetFont('Arial', 'B', 16);
            $this->SetTextColor(30, 60, 114);
            $this->Cell(0, 10, 'Task Report', 0, 1, 'C');
            $this->Ln(5);
        }
        
        function Footer() {
            $this->SetY(-15);
            $this->SetFont('Arial', 'I', 8);
            $this->SetTextColor(128);
            $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
        }
        
        function InfoSection($label, $value) {
            $this->SetFont('Arial', 'B', 10);
            $this->SetTextColor(60);
            $this->Cell(40, 6, $label . ':', 0, 0);
            $this->SetFont('Arial', '', 10);
            $this->SetTextColor(0);
            $this->Cell(0, 6, $value, 0, 1);
        }
        
        function TaskTable($header, $data) {
            // Colors
            $this->SetFillColor(30, 60, 114);
            $this->SetTextColor(255);
            $this->SetDrawColor(128, 128, 128);
            $this->SetLineWidth(.3);
            $this->SetFont('Arial', 'B', 9);
            
            // Column widths: Date, Project, Task Description, Priority, Deadline, Status, Progress
            $w = array(30, 35, 75, 20, 25, 25, 15);
            
            // Header row
            for($i = 0; $i < count($header); $i++) {
                $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
            }
            $this->Ln();
            
            // Data rows
            $this->SetTextColor(0);
            $this->SetFont('Arial', '', 8);
            $fill = false;
            
            foreach($data as $row) {
                // Sanitize and encode
                $date       = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['date']);
                $project    = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['project']);
                $task       = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['task']);
                $priority   = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['priority']);
                $deadline   = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['deadline']);
                $status     = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['status']);
                $completion = str_replace('%', '', $row['completion']) . '%';

                // Calculate row height based on tallest wrapping column
                $nb = max(
                    $this->NbLines($w[0], $date),
                    $this->NbLines($w[1], $project),
                    $this->NbLines($w[2], $task),
                    $this->NbLines($w[3], $priority),
                    $this->NbLines($w[4], $deadline),
                    $this->NbLines($w[5], $status),
                    $this->NbLines($w[6], $completion),
                    1
                );
                $h = 6 * $nb;
                
                // Page break check — reprint header if needed
                if($this->GetY() + $h > $this->PageBreakTrigger) {
                    $this->AddPage($this->CurOrientation);
                    $this->SetFillColor(30, 60, 114);
                    $this->SetTextColor(255);
                    $this->SetFont('Arial', 'B', 9);
                    for($i = 0; $i < count($header); $i++) {
                        $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
                    }
                    $this->Ln();
                    $this->SetTextColor(0);
                    $this->SetFont('Arial', '', 8);
                }
                
                $x = $this->GetX();
                $y = $this->GetY();
                $fillMode = $fill ? 'FD' : 'D';
                
                if($fill) $this->SetFillColor(248, 249, 250);
                
                // Date
                $this->Rect($x, $y, $w[0], $h, $fillMode);
                $this->SetXY($x + 1, $y + 1);
                $this->MultiCell($w[0] - 2, 6, $date, 0, 'L');
                
                // Project
                $this->Rect($x + $w[0], $y, $w[1], $h, $fillMode);
                $this->SetXY($x + $w[0] + 1, $y + 1);
                $this->MultiCell($w[1] - 2, 6, $project, 0, 'L');
                
                // Task Description (full text, no truncation)
                $this->Rect($x + $w[0] + $w[1], $y, $w[2], $h, $fillMode);
                $this->SetXY($x + $w[0] + $w[1] + 1, $y + 1);
                $this->MultiCell($w[2] - 2, 6, $task, 0, 'L');
                
                // Priority (colored text)
                $pColor = $this->getPriorityColor($row['priority']);
                $this->Rect($x + $w[0] + $w[1] + $w[2], $y, $w[3], $h, $fillMode);
                $this->SetTextColor($pColor[0], $pColor[1], $pColor[2]);
                $this->SetXY($x + $w[0] + $w[1] + $w[2] + 1, $y + 1);
                $this->MultiCell($w[3] - 2, 6, $priority, 0, 'C');
                $this->SetTextColor(0);
                
                // Deadline
                $this->Rect($x + $w[0] + $w[1] + $w[2] + $w[3], $y, $w[4], $h, $fillMode);
                $this->SetXY($x + $w[0] + $w[1] + $w[2] + $w[3] + 1, $y + 1);
                $this->MultiCell($w[4] - 2, 6, $deadline, 0, 'L');
                
                // Status (colored text)
                $sColor = $this->getStatusColor($row['status']);
                $this->Rect($x + $w[0] + $w[1] + $w[2] + $w[3] + $w[4], $y, $w[5], $h, $fillMode);
                $this->SetTextColor($sColor[0], $sColor[1], $sColor[2]);
                $this->SetXY($x + $w[0] + $w[1] + $w[2] + $w[3] + $w[4] + 1, $y + 1);
                $this->MultiCell($w[5] - 2, 6, $status, 0, 'C');
                $this->SetTextColor(0);
                
                // Completion
                $this->Rect($x + $w[0] + $w[1] + $w[2] + $w[3] + $w[4] + $w[5], $y, $w[6], $h, $fillMode);
                $this->SetXY($x + $w[0] + $w[1] + $w[2] + $w[3] + $w[4] + $w[5] + 1, $y + 1);
                $this->MultiCell($w[6] - 2, 6, $completion, 0, 'C');
                
                $this->SetXY($x, $y + $h);
                $fill = !$fill;
            }
        }

        function NbLines($w, $txt) {
            $cw = &$this->CurrentFont['cw'];
            if($w == 0) $w = $this->w - $this->rMargin - $this->x;
            $wmax = ($w - 2 * $this->cMargin) * 1000 / $this->FontSize;
            $s = str_replace("\r", '', $txt);
            $nb = strlen($s);
            if($nb > 0 && $s[$nb - 1] == "\n") $nb--;
            $sep = -1;
            $i = 0;
            $j = 0;
            $l = 0;
            $nl = 1;
            while($i < $nb) {
                $c = $s[$i];
                if($c == "\n") {
                    $i++;
                    $sep = -1;
                    $j = $i;
                    $l = 0;
                    $nl++;
                    continue;
                }
                if($c == ' ') $sep = $i;
                $l += $cw[$c];
                if($l > $wmax) {
                    if($sep == -1) {
                        if($i == $j) $i++;
                    } else $i = $sep + 1;
                    $sep = -1;
                    $j = $i;
                    $l = 0;
                    $nl++;
                } else $i++;
            }
            return $nl;
        }
        
        function getPriorityColor($priority) {
            switch($priority) {
                case 'Critical': return array(74, 20, 140);
                case 'High': return array(211, 47, 47);
                case 'Medium': return array(245, 124, 0);
                case 'Low': return array(25, 118, 210);
                default: return array(0, 0, 0);
            }
        }
        
        function getStatusColor($status) {
            switch($status) {
                case 'Completed': return array(56, 142, 60);
                case 'In Progress': return array(25, 118, 210);
                case 'On Hold': return array(245, 124, 0);
                default: return array(100, 100, 100);
            }
        }
    }
    
    $pdf = new PDF();
    $pdf->AddPage('L'); // Landscape
    
    // Report information
    $pdf->SetFont('Arial', '', 10);
    $pdf->InfoSection('Generated by', $username);
    $pdf->InfoSection('Date', $date);
    $pdf->InfoSection('Filter', $filter);
    if ($search) {
        $pdf->InfoSection('Search Query', $search);
    }
    $pdf->InfoSection('Total Tasks', count($data));
    $pdf->Ln(5);
    
    // Table
    $header = array('Date', 'Project', 'Task Description', 'Priority', 'Deadline', 'Status', 'Progress');
    $pdf->TaskTable($header, $data);
    
    $pdf->Output('D', 'tasks_report_' . date('Y-m-d_His') . '.pdf');
    exit();
}
?>