<?php
require_once 'config.php';
requireLogin();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: index.php');
    exit();
}

$format = $_POST['format'] ?? 'pdf';
$search = $_POST['search'] ?? '';
$dateFrom = $_POST['date_from'] ?? '';
$dateTo = $_POST['date_to'] ?? '';
$workMode = $_POST['work_mode'] ?? '';
$data = json_decode($_POST['data'], true);

if (empty($data)) {
    header('Location: index.php');
    exit();
}

$username = $_SESSION['username'];
$date = date('Y-m-d H:i:s');

if ($format === 'excel') {
    // Export as Excel (CSV format)
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="job_applications_report_' . date('Y-m-d_His') . '.csv"');
    
    $output = fopen('php://output', 'w');
    
    // Add report header
    fputcsv($output, ['Job Applications Report']);
    fputcsv($output, ['Generated by: ' . $username]);
    fputcsv($output, ['Date: ' . $date]);
    if ($dateFrom && $dateTo) {
        fputcsv($output, ['Date Range: ' . $dateFrom . ' to ' . $dateTo]);
    } elseif ($dateFrom) {
        fputcsv($output, ['From Date: ' . $dateFrom]);
    } elseif ($dateTo) {
        fputcsv($output, ['To Date: ' . $dateTo]);
    }
    if ($workMode) {
        fputcsv($output, ['Work Mode: ' . $workMode]);
    }
    if ($search) {
        fputcsv($output, ['Search Query: ' . $search]);
    }
    fputcsv($output, ['Total Applications: ' . count($data)]);
    fputcsv($output, []); // Empty row
    
    // Add column headers
    fputcsv($output, ['Job Title', 'Company', 'Date Applied', 'Work Mode', 'Job Description', 'Image']);
    
    // Add data rows
    foreach ($data as $row) {
        fputcsv($output, [
            $row['job_title'],
            $row['company'],
            $row['date_applied'],
            $row['work_mode'],
            $row['job_description'],
            $row['has_image'] ? 'Yes' : 'No'
        ]);
    }
    
    fclose($output);
    exit();
}

if ($format === 'pdf') {
    // Export as PDF using FPDF
    require_once('fpdf/fpdf.php');
    
    class PDF extends FPDF {
        function Header() {
            $this->SetFont('Arial', 'B', 16);
            $this->SetTextColor(156, 39, 176); // Purple color for job applications
            $this->Cell(0, 10, 'Job Applications Report', 0, 1, 'C');
            $this->Ln(5);
        }
        
        function Footer() {
            $this->SetY(-15);
            $this->SetFont('Arial', 'I', 8);
            $this->SetTextColor(128);
            $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
        }
        
        function InfoSection($label, $value) {
            $this->SetFont('Arial', 'B', 10);
            $this->SetTextColor(60);
            $this->Cell(40, 6, $label . ':', 0, 0);
            $this->SetFont('Arial', '', 10);
            $this->SetTextColor(0);
            $this->Cell(0, 6, $value, 0, 1);
        }
        
        function JobApplicationTable($header, $data) {
            // Colors
            $this->SetFillColor(156, 39, 176); // Purple
            $this->SetTextColor(255);
            $this->SetDrawColor(128, 128, 128);
            $this->SetLineWidth(.3);
            $this->SetFont('Arial', 'B', 9);
            
            // Column widths: Job Title, Company, Date Applied, Work Mode, Description
            $w = array(50, 45, 30, 25, 115);
            
            // Header row
            for($i = 0; $i < count($header); $i++) {
                $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
            }
            $this->Ln();
            
            // Data rows
            $this->SetTextColor(0);
            $this->SetFont('Arial', '', 8);
            $fill = false;
            
            foreach($data as $row) {
                // Sanitize and encode (full description, no truncation)
                $jobTitle    = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['job_title']);
                $company     = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['company']);
                $dateApplied = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['date_applied']);
                $workMode    = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['work_mode']);
                $description = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $row['job_description']);

                // Calculate row height based on tallest wrapping column
                $nb = max(
                    $this->NbLines($w[0], $jobTitle),
                    $this->NbLines($w[1], $company),
                    $this->NbLines($w[2], $dateApplied),
                    $this->NbLines($w[3], $workMode),
                    $this->NbLines($w[4], $description),
                    1
                );
                $h = 6 * $nb;
                
                // Page break check — reprint header if needed
                if($this->GetY() + $h > $this->PageBreakTrigger) {
                    $this->AddPage($this->CurOrientation);
                    $this->SetFillColor(156, 39, 176);
                    $this->SetTextColor(255);
                    $this->SetFont('Arial', 'B', 9);
                    for($i = 0; $i < count($header); $i++) {
                        $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
                    }
                    $this->Ln();
                    $this->SetTextColor(0);
                    $this->SetFont('Arial', '', 8);
                }
                
                $x = $this->GetX();
                $y = $this->GetY();
                $fillMode = $fill ? 'FD' : 'D';
                
                if($fill) $this->SetFillColor(248, 249, 250);
                
                // Job Title
                $this->Rect($x, $y, $w[0], $h, $fillMode);
                $this->SetXY($x + 1, $y + 1);
                $this->MultiCell($w[0] - 2, 6, $jobTitle, 0, 'L');
                
                // Company
                $this->Rect($x + $w[0], $y, $w[1], $h, $fillMode);
                $this->SetXY($x + $w[0] + 1, $y + 1);
                $this->MultiCell($w[1] - 2, 6, $company, 0, 'L');
                
                // Date Applied
                $this->Rect($x + $w[0] + $w[1], $y, $w[2], $h, $fillMode);
                $this->SetXY($x + $w[0] + $w[1] + 1, $y + 1);
                $this->MultiCell($w[2] - 2, 6, $dateApplied, 0, 'C');
                
                // Work Mode (colored text)
                $wmColor = $this->getWorkModeColor($row['work_mode']);
                $this->Rect($x + $w[0] + $w[1] + $w[2], $y, $w[3], $h, $fillMode);
                $this->SetTextColor($wmColor[0], $wmColor[1], $wmColor[2]);
                $this->SetXY($x + $w[0] + $w[1] + $w[2] + 1, $y + 1);
                $this->MultiCell($w[3] - 2, 6, $workMode, 0, 'C');
                $this->SetTextColor(0);
                
                // Job Description (full text)
                $this->Rect($x + $w[0] + $w[1] + $w[2] + $w[3], $y, $w[4], $h, $fillMode);
                $this->SetXY($x + $w[0] + $w[1] + $w[2] + $w[3] + 1, $y + 1);
                $this->MultiCell($w[4] - 2, 6, $description, 0, 'L');
                
                $this->SetXY($x, $y + $h);
                $fill = !$fill;
            }
        }

        function NbLines($w, $txt) {
            $cw = &$this->CurrentFont['cw'];
            if($w == 0) $w = $this->w - $this->rMargin - $this->x;
            $wmax = ($w - 2 * $this->cMargin) * 1000 / $this->FontSize;
            $s = str_replace("\r", '', $txt);
            $nb = strlen($s);
            if($nb > 0 && $s[$nb - 1] == "\n") $nb--;
            $sep = -1;
            $i = 0;
            $j = 0;
            $l = 0;
            $nl = 1;
            while($i < $nb) {
                $c = $s[$i];
                if($c == "\n") {
                    $i++;
                    $sep = -1;
                    $j = $i;
                    $l = 0;
                    $nl++;
                    continue;
                }
                if($c == ' ') $sep = $i;
                $l += $cw[$c];
                if($l > $wmax) {
                    if($sep == -1) {
                        if($i == $j) $i++;
                    } else $i = $sep + 1;
                    $sep = -1;
                    $j = $i;
                    $l = 0;
                    $nl++;
                } else $i++;
            }
            return $nl;
        }
        
        function getWorkModeColor($workMode) {
            switch($workMode) {
                case 'Onsite': return array(25, 118, 210); // Blue
                case 'Hybrid': return array(245, 124, 0); // Orange
                case 'Remote': return array(56, 142, 60); // Green
                default: return array(0, 0, 0);
            }
        }
    }
    
    $pdf = new PDF();
    $pdf->AddPage('L'); // Landscape
    
    // Report information
    $pdf->SetFont('Arial', '', 10);
    $pdf->InfoSection('Generated by', $username);
    $pdf->InfoSection('Date', $date);
    if ($dateFrom && $dateTo) {
        $pdf->InfoSection('Date Range', $dateFrom . ' to ' . $dateTo);
    } elseif ($dateFrom) {
        $pdf->InfoSection('From Date', $dateFrom);
    } elseif ($dateTo) {
        $pdf->InfoSection('To Date', $dateTo);
    }
    if ($workMode) {
        $pdf->InfoSection('Work Mode Filter', $workMode);
    }
    if ($search) {
        $pdf->InfoSection('Search Query', $search);
    }
    $pdf->InfoSection('Total Applications', count($data));
    $pdf->Ln(5);
    
    // Table
    $header = array('Job Title', 'Company', 'Date Applied', 'Work Mode', 'Job Description');
    $pdf->JobApplicationTable($header, $data);
    
    $pdf->Output('D', 'job_applications_report_' . date('Y-m-d_His') . '.pdf');
    exit();
}
?>
