<?php
require_once 'config.php';
requireLogin();

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    header('Location: index.php');
    exit();
}

$format = $_POST['format'] ?? 'pdf';
$filter = $_POST['filter'] ?? 'All';
$search = $_POST['search'] ?? '';
$data = json_decode($_POST['data'], true);

if (empty($data)) {
    header('Location: index.php');
    exit();
}

$username = $_SESSION['username'];
$date = date('Y-m-d H:i:s');

if ($format === 'excel') {
    // Export as Excel (CSV format)
    header('Content-Type: text/csv');
    header('Content-Disposition: attachment; filename="tasks_report_' . date('Y-m-d_His') . '.csv"');
    
    $output = fopen('php://output', 'w');
    
    // Add report header
    fputcsv($output, ['Task Report']);
    fputcsv($output, ['Generated by: ' . $username]);
    fputcsv($output, ['Date: ' . $date]);
    fputcsv($output, ['Filter: ' . $filter]);
    if ($search) {
        fputcsv($output, ['Search Query: ' . $search]);
    }
    fputcsv($output, ['Total Tasks: ' . count($data)]);
    fputcsv($output, []); // Empty row
    
    // Add column headers
    fputcsv($output, ['Date', 'Project', 'Task Description', 'Priority', 'Deadline', 'Status', 'Completion']);
    
    // Add data rows
    foreach ($data as $row) {
        fputcsv($output, [
            $row['date'],
            $row['project'],
            $row['task'],
            $row['priority'],
            $row['deadline'],
            $row['status'],
            $row['completion']
        ]);
    }
    
    fclose($output);
    exit();
}

if ($format === 'pdf') {
    // Export as PDF using FPDF
    require_once('fpdf/fpdf.php');
    
    class PDF extends FPDF {
        function Header() {
            $this->SetFont('Arial', 'B', 16);
            $this->SetTextColor(30, 60, 114);
            $this->Cell(0, 10, 'Task Report', 0, 1, 'C');
            $this->Ln(5);
        }
        
        function Footer() {
            $this->SetY(-15);
            $this->SetFont('Arial', 'I', 8);
            $this->SetTextColor(128);
            $this->Cell(0, 10, 'Page ' . $this->PageNo(), 0, 0, 'C');
        }
        
        function InfoSection($label, $value) {
            $this->SetFont('Arial', 'B', 10);
            $this->SetTextColor(60);
            $this->Cell(40, 6, $label . ':', 0, 0);
            $this->SetFont('Arial', '', 10);
            $this->SetTextColor(0);
            $this->Cell(0, 6, $value, 0, 1);
        }
        
        function TaskTable($header, $data) {
            // Colors
            $this->SetFillColor(30, 60, 114);
            $this->SetTextColor(255);
            $this->SetDrawColor(200, 200, 200);
            $this->SetLineWidth(.3);
            $this->SetFont('Arial', 'B', 9);
            
            // Header
            $w = array(25, 30, 60, 20, 25, 25, 20);
            for($i = 0; $i < count($header); $i++) {
                $this->Cell($w[$i], 7, $header[$i], 1, 0, 'C', true);
            }
            $this->Ln();
            
            // Data
            $this->SetFillColor(248, 249, 250);
            $this->SetTextColor(0);
            $this->SetFont('Arial', '', 8);
            
            $fill = false;
            foreach($data as $row) {
                $this->Cell($w[0], 6, $row['date'], 'LR', 0, 'L', $fill);
                $this->Cell($w[1], 6, $row['project'], 'LR', 0, 'L', $fill);
                
                // Truncate long task descriptions
                $task = strlen($row['task']) > 35 ? substr($row['task'], 0, 35) . '...' : $row['task'];
                $this->Cell($w[2], 6, $task, 'LR', 0, 'L', $fill);
                
                // Priority color coding
                $priority = $row['priority'];
                $color = $this->getPriorityColor($priority);
                $this->SetTextColor($color[0], $color[1], $color[2]);
                $this->Cell($w[3], 6, $priority, 'LR', 0, 'C', $fill);
                $this->SetTextColor(0);
                
                $this->Cell($w[4], 6, $row['deadline'], 'LR', 0, 'L', $fill);
                
                // Status color coding
                $status = $row['status'];
                $color = $this->getStatusColor($status);
                $this->SetTextColor($color[0], $color[1], $color[2]);
                $this->Cell($w[5], 6, $status, 'LR', 0, 'C', $fill);
                $this->SetTextColor(0);
                
                $this->Cell($w[6], 6, $row['completion'], 'LR', 0, 'C', $fill);
                
                $this->Ln();
                $fill = !$fill;
            }
            $this->Cell(array_sum($w), 0, '', 'T');
        }
        
        function getPriorityColor($priority) {
            switch($priority) {
                case 'Critical': return array(74, 20, 140);
                case 'High': return array(211, 47, 47);
                case 'Medium': return array(245, 124, 0);
                case 'Low': return array(25, 118, 210);
                default: return array(0, 0, 0);
            }
        }
        
        function getStatusColor($status) {
            switch($status) {
                case 'Completed': return array(56, 142, 60);
                case 'In Progress': return array(25, 118, 210);
                case 'On Hold': return array(245, 124, 0);
                default: return array(100, 100, 100);
            }
        }
    }
    
    $pdf = new PDF();
    $pdf->AddPage('L'); // Landscape
    
    // Report information
    $pdf->SetFont('Arial', '', 10);
    $pdf->InfoSection('Generated by', $username);
    $pdf->InfoSection('Date', $date);
    $pdf->InfoSection('Filter', $filter);
    if ($search) {
        $pdf->InfoSection('Search Query', $search);
    }
    $pdf->InfoSection('Total Tasks', count($data));
    $pdf->Ln(5);
    
    // Table
    $header = array('Date', 'Project', 'Task Description', 'Priority', 'Deadline', 'Status', 'Progress');
    $pdf->TaskTable($header, $data);
    
    $pdf->Output('D', 'tasks_report_' . date('Y-m-d_His') . '.pdf');
    exit();
}
?>